language: python
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
services:
  - postgresql
before_script:
  - cd mockserver
  - psql -c 'create database mockserver_tests' -U postgres
env:
  global:
      - DATABASE_URL="postgres://postgres@localhost:5432/mockserver_tests"
script:
  - echo "starting pipeline"
jobs:
  include:
    - stage: unit tests
      script: python manage.py test --testrunner=test_settings.nodb_runner.NoDbTestRunner
    - stage: lint
      script: flake8
